src/Louvre/BilletterieBundle/Entity/Billet.php
<?php

namespace Louvre\BilletterieBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Billet
 *
 * @ORM\Table(name="bl_billet")
 * @ORM\Entity(repositoryClass="Louvre\BilletterieBundle\Repository\BilletRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Billet
{

    /**
    * @ORM\ManyToOne(targetEntity="Louvre\BilletterieBundle\Entity\Reservation", inversedBy="billets", cascade={"persist"})
    * @ORM\JoinColumn(nullable=false)
    */
    private $reservation;
    
    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=255)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="pays", type="string", length=255)
     */
    private $pays;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datenaissance", type="date")
     */
    private $datenaissance;

    /**
     * @var bool
     *
     * @ORM\Column(name="reduit", type="boolean")
     */
    private $reduit;

    /**
     * @var string
     *
     * @ORM\Column(name="prix", type="decimal", precision=6, scale=2)
     */
    private $prix;

    /**
     * Billet constructor.
     */
    public function __construct()
    {
        $this->datenaissance = new\datetime();

    }
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Billet
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return Billet
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set pays
     *
     * @param string $pays
     *
     * @return Billet
     */
    public function setPays($pays)
    {
        $this->pays = $pays;

        return $this;
    }

    /**
     * Get pays
     *
     * @return string
     */
    public function getPays()
    {
        return $this->pays;
    }

    /**
     * Set datenaissance
     *
     * @param \DateTime $datenaissance
     *
     * @return Billet
     */
    public function setDatenaissance($datenaissance)
    {
        $this->datenaissance = $datenaissance;

        return $this;
    }

    /**
     * Get datenaissance
     *
     * @return \DateTime
     */
    public function getDatenaissance()
    {
        return $this->datenaissance;
    }

    /**
     * Set reduit
     *
     * @param boolean $reduit
     *
     * @return Billet
     */
    public function setReduit($reduit)
    {
        $this->reduit = $reduit;

        return $this;
    }

    /**
     * Get reduit
     *
     * @return bool
     */
    public function getReduit()
    {
        return $this->reduit;
    }

    /**
     * Set prix
     *
     * @param string $prix
     *
     * @return Billet
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * Get prix
     *
     * @return string
     */
    public function getPrix()
    {
        return $this->prix;
    }
    
    public function setReservation(Reservation $reservation)
    {
        $this->reservation = $reservation;

        return $this;
    }

    /**
     * Get prix
     *
     * @return string
     */
    public function getReservationx()
    {
        return $this->reservation;
    }
}

src/Louvre/BilletterieBundle/Entity/Reservation.php
<?php

namespace Louvre\BilletterieBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * Reservation
 *
 * @ORM\Table(name="bl_reservation")
 * @ORM\Entity(repositoryClass="Louvre\BilletterieBundle\Repository\ReservationRepository")
 * @ORM\HasLifecycleCallbacks()

 */
class Reservation
{
    /**
    * @ORM\OneToMany(targetEntity="Louvre\BilletterieBundle\Entity\Billet", mappedBy="reservation", cascade={"persist"})
    */
    
    private $billets;
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="code", type="string", length=13, unique=true)
     */
    private $code;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateresa", type="datetime")
     */
    private $dateresa;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datevisite", type="date")
     */
    private $datevisite;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="demijournee", type="boolean")
     */
    private $demijournee;

    /**
     * Reservation constructor.
     */
    public function __construct()
    {
        $this->dateresa = new\datetime();
        $this->payement = FALSE;
        $this->code = uniqid();
        $this->datevisite = new \Datetime();

    }
    
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set code
     *
     * @param string $code
     *
     * @return Reservation
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set dateresa
     *
     * @param \DateTime $dateresa
     *
     * @return Reservation
     */
    public function setDateresa($dateresa)
    {
        $this->dateresa = $dateresa;

        return $this;
    }

    /**
     * Get dateresa
     *
     * @return \DateTime
     */
    public function getDateresa()
    {
        return $this->dateresa;
    }

    /**
     * Set datevisite
     *
     * @param \DateTime $datevisite
     *
     * @return Reservation
     */
    public function setDatevisite($datevisite)
    {
        $this->datevisite = $datevisite;

        return $this;
    }

    /**
     * Get datevisite
     *
     * @return \DateTime
     */
    public function getDatevisite()
    {
        return $this->datevisite;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Reservation
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set demijournee
     *
     * @param boolean $demijournee
     *
     * @return Reservation
     */
    public function setDemijournee($demijournee)
    {
        $this->demijournee = $demijournee;

        return $this;
    }

    /**
     * Get demijournee
     *
     * @return bool
     */
    public function getDemijournee()
    {
        return $this->demijournee;
    }
    

    /**
     * Add billet
     *
     * @param \Louvre\BilletterieBundle\Entity\Billet $billet
     *
     * @return Reservation
     */
    public function addBillet(\Louvre\BilletterieBundle\Entity\Billet $billet)
    {
        $this->billets[] = $billet;
        $billet->setReservation($this);
        return $this;
    }

    /**
     * Remove billet
     *
     * @param \Louvre\BilletterieBundle\Entity\Billet $billet
     */
    public function removeBillet(\Louvre\BilletterieBundle\Entity\Billet $billet)
    {
        $this->billets->removeElement($billet);
    }

    /**
     * Get billet
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBillets()
    {
        return $this->billets;
    }
    
    public function getPrixReservation()
    {
        $prixTotal= 0;
        foreach($this->billets as $billet) {
            $prixTotal += $billet->getPrix();
        }   
        return $prixTotal;
    } 
}

src/Louvre/BilletterieBundle/Form/Type/BilletType.php
<?php

namespace Louvre\BilletterieBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BilletType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',          TextType::class)
            ->add('prenom',       TextType::class, array(
                'label'     => 'Prénom'
            ))
            ->add('pays',         CountryType::class, array(
                'preferred_choices' => array('FR')
            ))
                
            ->add('datenaissance',BirthdayType::class, array(
                'label'  => 'Date de naissance',
                'placeholder' => array('day' => 'Jour','month' => 'Mois','year' => 'Annee')))
            ->add('reduit',CheckboxType::class, array(
                'required' => false,
                'attr' => ['class' => 'check-reduit']
                ));
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Louvre\BilletterieBundle\Entity\Billet'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'louvre_billetteriebundle_billet';
    }


}

src/Louvre/BilletterieBundle/Controller/BilletController.php
<?php

// src/Louvre/BilletterieBundle/Controller/BilletController.php

namespace Louvre\BilletterieBundle\Controller;

use Louvre\BilletterieBundle\Entity\Reservation;
use Louvre\BilletterieBundle\Form\Type\ReservationType;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;





class BilletController extends Controller
{
    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function indexAction(Request $request)
    {
        //Gestion des variables pour JQUERY
        $this->get('acme.js_vars')->jour_fermeture_num = $this->container->getParameter('jour_fermeture_num');
        $this->get('acme.js_vars')->mi_journee = $this->container->getParameter('mi_journee');
        $this->get('acme.js_vars')->fermeture_annuelle = $this->container->getParameter('fermeture_annuelle');

        //On créé un objet Réservation
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            // On vérifie la capacité du musée sur la date choisie
            if ($this->get('louvre_billetterie.services')->calculCapacite($reservation) === false)
            {
                $this->addFlash("alert", "Plus de place disponible à cette date, veuillez choisir une autre date");
                return $this->redirectToRoute("louvre_billetterie_home");
            }

            if ($form->isValid()) {
                //On calcule le prix de chaque billet
                $this->get('louvre_billetterie.services')->calculPrixBillets($reservation);
                // On enregistre la réservation en Session
                $this->get('session')->set('resa', $reservation);
                $this->addFlash('succes', 'Votre Commande a bien été enregistrée. Pour la finaliser, vous devez maintenant proceder au payement');
                // On redirige vers la page de paiement
                return $this->redirectToRoute('louvre_billetterie_paiement');
            }
        }
        //On affiche le Template
        return $this->render('LouvreBilletterieBundle:Billet:index.html.twig', array('form' => $form->createView()));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function payerAction(Request $request)
    {
        $session = $this->get('session');
        if ($session->get('resa')) {
            //On récupère la réservation session
            $reservation = $session->get('resa');

            //On affiche le Template la page de payement
            return $this->render('LouvreBilletterieBundle:Billet:payer.html.twig', array(
                'reservation' => $reservation
            ));
        } else {
            return $this->redirectToRoute("louvre_billetterie_home");
        }
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function checkoutAction(Request $request)
    {
        $session = $this->get('session');
        if ($session->get('resa')) {
            //On récupère la réservation session
            $reservation = $session->get('resa');

            \Stripe\Stripe::setApiKey("sk_test_ASWzmBLDGmEGV28r8VxmIs6Q");
            // Get the credit card details submitted by the form
            $token = $request->request->get('stripeToken');
            // Create a charge: this will charge the user's card
            try {
                \Stripe\Charge::create(array("amount" => $reservation->getPrixReservation() * 100, "currency" => "eur", "source" => $token, "description" => "Paiement Stripe - Résalouvre"));
                //On enregistre en base de données

                $em = $this->getDoctrine()->getManager();
                $em->persist($reservation);
                $em->flush();
                return $this->redirectToRoute("louvre_billetterie_success");

            } catch (\Stripe\Error\Card $e) {
                $this->addFlash("alert", "Votre paiement n'a pas été accepté, veuillez ré-essayer");
                return $this->redirectToRoute("louvre_billetterie_paiement");
            }
        } else {
            return $this->redirectToRoute("louvre_billetterie_home");
        }
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function successAction(Request $request)
    {
        $session = $this->get('session');
        if ($session->get('resa')->getId() !== null) {
            //La réservation a été enregistrée en base
            $reservation = $session->get('resa');
            //Envoi des billets par émail
            $this->get('louvre_billetterie.services')->sendEmail($reservation);
            $this->addFlash("succes", "Félicitations, votre paiement a bien été enregistré ! Un email contenant vos billets vous a été envoyé");
            $session->invalidate('resa');

            //On affiche le Template la page de success
            return $this->render('LouvreBilletterieBundle:Billet:success.html.twig');
        } else {
            //Cas de tentative de fraude
            $this->addFlash("alert", "Votre paiement n'a pas été accepté, veuillez ré-essayer");
            return $this->redirectToRoute("louvre_billetterie_paiement");
        }
    }
}

src/Louvre/BilletterieBundle/Resources/views/Billet/commande.html.twig
{# src/Louvre/BilletterieBundle/Resources/views/Billet/commande.html.twig #}
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Votre commande</h3>
    </div>
    <div class="panel-body">
        {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
        <div class="well">
            {{ form_errors(form) }}
            <div class="form-group">
                {{ form_label(form.datevisite, "Date de visite", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.datevisite) }}
                <div class="col-sm-9">
                    {{ form_widget(form.datevisite, {'attr': {'class': 'form-control js-datepicker'}}) }}
                </div>
            </div>
            <div class="form-group">
                {{ form_label(form.demijournee, "Type de billet", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.demijournee) }}
                <div class="col-sm-9">
                    {{ form_widget(form.demijournee, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group">
                {{ form_label(form.email, "Votre email", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.email) }}
                <div class="col-sm-9">
                    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label" >Nombre de billets</label>
                <div class="col-sm-9">
                    <input type="text" name="nb_billet" id="nb_billet" class="form-control">
                </div>
            </div>
        </div>
        <div class="well">
            {{ form_widget(form.billets) }}
            {{ form_rest(form) }}
            {{ form_widget(form.Valider, {'attr': {'class': 'btn btn-primary'}}) }}
            {{ form_end(form) }}
        </div>
    </div>
</div>

src/Louvre/BilletterieBundle/Resources/views/Billet/email.html.twig
{# src/Louvre/BilletterieBundle/Resources/views/Billet/email.html.twig #}
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      {% block stylesheets %}
        {# On charge le CSS de bootstrap depuis le site directement #}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      {% endblock %}
    </head>

    <body>
        <div class="container">
            <div id="header" class="jumbotron">
                <img src="{{ absolute_url(asset("http://www.louvre.fr/sites/all/themes/louvre/img/data/logo-louvre.jpg")) }}" width="182" height="55" alt="Logo du musée du Louvre - Page d’accueil du site internet du musée du Louvre (Paris, France) " /></a>
            </div>
            <div class="row">
                <div id="content" class="col-md-12">
                    <H2>Billetterie du Louvre</h2>
                    <h3>Bonjour {{ reservation.email }}</h3>
                    Votre réservation a bien été enregistrée. Veuillez trouver ci-dessous vos billets. <br>
                    Imprimez cet email et présentez le à l'accueil du Louvre.
                    <p>
                    Votre numéro de réservation : {{ reservation.code }} <br>
                    Billets valables le : {{ reservation.datevisite |date('d/m/Y')}}
                    {% if reservation.demijournee == 1  %}
                        à partir de {{ mi_journee }} heure.
                    {% endif %}
                    <br>
                    Prix Total = {{ reservation.prixReservation }} €<br>
                    <h3>Vos Billets</h3>
                    {% for billet in reservation.billets %}
                        <li> {{ billet.nom }} {{ billet.prenom }} : {{ billet.prix }} €</li>
                    {% endfor %}
                </div>
            </div>
            <hr>
        </div>
    </body>
</html>

src/Louvre/BilletterieBundle/Resources/views/Billet/index.html.twig
{# src/Louvre/BilletterieBundle/Resources/views/Billet/index.html.twig #}

{% extends "LouvreBilletterieBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block louvrebilleterie_body %}
    {#Gestion des FlashMessages#}
    {% for flashMessage in app.session.flashbag.get('succes') %}
        <div class="alert alert-success">
            {{ flashMessage }}
        </div>
    {% endfor %}
    {% for flashMessage in app.session.flashbag.get('alert') %}
        <div class="alert alert-danger">
            {{ flashMessage }}
        </div>
    {% endfor %}

    <div class="row">
        <div class="col-lg-7">
            {% include 'LouvreBilletterieBundle:Billet:commande.html.twig' %}
        </div>
        <div class="col-lg-5">
            {% include 'LouvreBilletterieBundle:Billet:panier.html.twig' %}
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
{%  endblock %}

src/Louvre/BilletterieBundle/Resources/views/Billet/message.html.twig
{# src/Louvre/BilletterieBundle/Resources/views/Billet/commande.html.twig #}
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Message</h3>
    </div>
    <div class="panel-body">
        <div class="well">
            {% for flashMessage in app.session.flashbag.get('succes') %}
                <div class="alert alert-success">
                    {{ flashMessage }}
                </div>
            {% endfor %}
            {% for flashMessage in app.session.flashbag.get('alert') %}
                <div class="alert alert-danger">
                    {{ flashMessage }}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

src/Louvre/BilletterieBundle/Resources/views/Billet/panier.html.twig
{# src/Louvre/BilletterieBundle/Resources/views/Billet/panier.html.twig #}
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Votre panier</h3>
    </div>
    <div class="panel-body">
         {% if reservation is defined %}
            Votre numéro de réservation : {{ reservation.code }} </br>
            Billets valables le : {{ reservation.datevisite |date('d/m/Y')}}
            {% if reservation.demijournee == 1  %}
                à partir de {{ mi_journee }} heure.
            {% endif %}
            </br>
            Prix Total = {{ reservation.prixReservation }} €</br>
            <h3>Vos Billets</h3>
            {% for billet in reservation.billets %}
                <li> {{ billet.nom }} {{ billet.prenom }} : {{ billet.prix }} €</li>
            {% endfor %}
            <form action="{{ path('louvre_billetterie_checkout') }}" method="POST">
                <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="pk_test_tIgQXIcOuJRssbXZnEAalH0m"
                    data-amount="{{ reservation.prixReservation * 100}} "
                    data-name="Resalouvre"
                    data-email="{{ reservation.email }}"
                    data-description="Module de paiement"
                    data-locale="auto"
                    data-image="{{ asset("images/logo-louvre.jpg") }}"
                    data-label="Payer avec ma CB"
                    data-currency="eur">
                </script>
            </form>
        {% else %}
            <p>Votre panier est vide</p>

        {% endif %}
    </div>
</div>

src/Louvre/BilletterieBundle/Resources/views/Billet/payer.html.twig
{# src/Louvre/BilletterieBundle/Resources/views/Billet/payer.html.twig #}

{% extends "LouvreBilletterieBundle::layout.html.twig" %}

{% block title %}
  Payer - {{ parent() }}
{% endblock %}

{% block louvrebilleterie_body %}


<div class="row">
    <div class="col-lg-7">
        {% include 'LouvreBilletterieBundle:Billet:message.html.twig' %}
    </div>
    <div class="col-lg-5">
        {% include 'LouvreBilletterieBundle:Billet:panier.html.twig' %}
    </div>
</div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}

{%  endblock %}    

src/Louvre/BilletterieBundle/Resources/views/Billet/success.html.twig
{# src/Louvre/BilletterieBundle/Resources/views/Billet/success.html.twig #}

{% extends "LouvreBilletterieBundle::layout.html.twig" %}

{% block title %}
  Succès - {{ parent() }}
{% endblock %}

{% block louvrebilleterie_body %}
    <div class="jumbotron">
        <center>
            <img src="{{ asset("images/succes.jpg") }}"  alt="Succès" /></a>
            <h2>Félicitation pour votre achat.</h2>
            <p>Vos billets vous ont été envoyés par email</p>
            <a class="btn btn-primary btn-lg" href="./">Retour à l'accueil</a>
        </center>
    </div>
  </body>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
{%  endblock %}